name: Python Build and Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build and Test Python
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine  # Install necessary tools

      - name: Build the distribution
        run: |
          python -m build  # Build source and wheel distributions

      - name: List files in dist directory
        run: ls -alh dist/

  publish-to-testpypi:
    name: Publish Python Package to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions

      - name: Publish to TestPyPI
        run: |
          python -m pip install --upgrade twine
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}